version: "3"

services:
    db:
        restart: always
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - graphql-network
    phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - graphql-network
            
networks: 
    graphql-network:
        driver: bridge